<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INPNRLT0375" failures="2" tests="3" name="Error Validation Test" time="25.687" errors="0" timestamp="2023-01-10T16:34:42 IST">
  <testcase classname="PageObject.ErrorValidationTest" name="ProductErrorvalidation" time="8.505"/>
  <testcase classname="PageObject.ErrorValidationTest" name="loginErrorvalidation" time="0.314">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect email or password. ]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password. ]
at PageObject.ErrorValidationTest.loginErrorvalidation(ErrorValidationTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorvalidation -->
  <testcase classname="PageObject.ErrorValidationTest" name="loginErrorvalidation" time="6.904">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)&amp;quot; because &amp;quot;ts&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)" because "ts" is null
at PageObject.BaseTest.getScreenShot(BaseTest.java:65)
at PageObject.Listeners.onTestFailure(Listeners.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorvalidation -->
</testsuite> <!-- Error Validation Test -->
